test:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'

development:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'

production:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'
