test:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'
  7:
    name: 'DHS'
  8:
    name: 'DOD'

development:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'
  7:
    name: 'USSS'
  8:
    name: 'DOD'

production:
  1:
    name: 'CBP'
  2:
    name: 'OPM'
  3:
    name: 'EOP'
  4:
    name: 'RRB'
  5:
    name: 'NGA'
  6:
    name: 'DOT'
  7:
    name: 'USSS'
  8:
    name: 'DOD'
